# App e servidor
spring.application.name=mvc-crud
server.port=8090

# Conexão com o banco de dados (Postgresql)
spring.datasource.url=jdbc:postgresql://localhost:5432/mvc-crud-database
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Config JPA & Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# SQL console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true